POST http://localhost:3000/posts/ HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYi5jb20iLCJpYXQiOjE1ODIyMTAxODgsImV4cCI6MTU4MjI5NjU4OH0.36RRkWKZfRuVm0fid9OYwbCMsmQeIkgnQHzCuuBKBgU
content-type: application/json

{
    "title": "After Authorization",
    "description": "123456",
    "author": "aryan",
    "authorUsername": "aryan"
}

###
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
    "email": "a@b.com",
    "password": "123456"
}

###

GET http://localhost:3000/posts HTTP/1.1
content-type: application/json
